### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by IGNRexI** [dounai2333/CSO2-ComboLauncher#1]
![image](https://user-images.githubusercontent.com/36341134/128077532-5b35eacf-b910-4baa-bd04-ced84a0ab3b5.png)
![image](https://user-images.githubusercontent.com/36341134/128077608-db54822f-ebe9-498d-868d-0b3b23961595.png)

???????????????????

**Comment by IGNRexI** [comment]
I tried for TEST purpose, error xd

**Comment by dounai2333** [comment]
https://stackoverflow.com/questions/22736582/provide-value-on-system-windows-baml2006-typeconvertermarkupextension-threw-a
search before you ask.
